[control_plane]
oss01 ansible_host=10.60.63.1 ansible_user=controlnode ansible_connection=local

[workers]
oss02 ansible_host=10.60.63.2 ansible_user=workernode1
oss03 ansible_host=10.60.63.5 ansible_user=workernode2
oss04 ansible_host=10.60.63.6 ansible_user=workernode3

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_become=true
ansible_become_method=sudo
